version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kestra-postgres
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    build:
      context: .          # current directory contains Dockerfile
      dockerfile: Dockerfile
    image: kestra-custom:latest
    container_name: kestra
    user: "root"
    command: server standalone
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"   # API + UI
      - "8081:8081"   # Executor metrics
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              enabled: false
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: /app/storage
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080
    volumes:
      - ./flows:/app/flows
      - ./storage:/app/storage
      - ./kestra-wd:/tmp/kestra-wd
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data:
  kestra-data:
